spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/sbip
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
logging:
  file:
    name: application.log